theme: jekyll-theme-minimal
title: PH142 Resource Hub
description: <img src="images/git_icon.jpg"> <br> <b>22. San Francisco, CA.</b><br><br>I've only been programming for a year, but it already feels like a lifetime. Palautatan means "statistics" in Tagalog.
