---
title: "Homework Format"
output: html_document
---

You will turn in your homework on Gradescope! In order to make grading matters efficient, please follow these guidelines. We will be able to get your homework back to you much faster!

## 1. Timeliness
Turn in your homework ON TIME. Gradescope will mark assignments late if they are turned in past the state hour, and we can "unmark" it as late. Aside from emergencies, there is no reason to not turn in work on time.

## 2. Formatting

### Displaying your answer
In RStudio, you will see 4 panes. Two of which are the Console (where answers may show up) and the Editor (where you write your code/answers). You must make sure that your KNIT version (your PDF file that you are going to turn in) displays answers to every question. Please, look at your homework PDF before turning it in!

### Clear separation between answers
Please provide a `\newpage` line between each of the questions on your homework, and do not delete it if it already exists. This will help you and the GSI's keep track of pages on Gradescope.

### R Markdown Cheat Sheet
RStudio has a cheat sheet <a href="https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf">here</a> for your styling needs. For this class, only look at #1-4.

## 3. Submission

### Assigning pages
Accurately assign each of your homework pages to the question that they correspond to. You will lose points if you don't!